### ISSUE TITLE
Samples

### ISSUE THREAD

**Issue by devlfm** [chadrem/amf_socket#1]
Hi,

Can you add a samples folder to the sources?

Thank you and good job!

**Comment by chadrem** [comment]
@devlfm Sorry there are no examples. I meant to do that, but never got around to it. I am currently busy with other projects so I don't currently have time to write up examples and test them.

At a high level, you use the ````AmfRpcSocket```` class to connect to a compatible server. You then ````deliver```` to send requests (or messages) to the server.  If the server sends you requests or messages then you listen for them with event handlers.

I hope this is somewhat helpful.
