### ISSUE TITLE
How to use custom class with amf_socket?

### ISSUE THREAD

**Issue by jimmymjing** [chadrem/amf_socket#2]
Hello,
Thanks so much for providing amf_socket. I see the way how to send and receive Objects between client an server. But how do I send back and force custom class objects? sendRequest() and sendMessage() functions can't be used to send custom class objects?

**Comment by chadrem** [comment]
@jimmymjing it sounds like you are asking how to use the class mapping feature of Flash. If so, you can find a very basic example on the amf_socket homepage:

https://github.com/chadrem/amf_socket#class-mapper

I haven't worked with custom classes in a long time, but last I remember you can find more information in Adobe's docs by searching for the ````registerClassAlias```` function.
